### ISSUE TITLE
How to make map-matching include the elevation data?

### ISSUE THREAD

**Issue by carlos-mg89** [graphhopper/map-matching#144]
I have tried to include the elevation data following the information I read in this forum post https://discuss.graphhopper.com/t/map-matching-with-elevation-data/2238/5

However, the elevation data is never included, and it actually seems that nothing is happening at all.

This is my config file:

```
graphhopper:
  datareader.file: map-data/leipzig_germany.osm.pbf
  graph.location: graph-cache
  graph.flag_encoders: hike
  prepare.ch.weightings: no
  graph.elevation.provider: multi
  graph.elevation.calc_mean: true
  graph.elevation.smoothing: true
  graph.elevation.cache_dir: ./srtmprovider/
  graph.elevation.dataaccess: RAM_STORE

server:
  applicationConnectors:
  - type: http
    port: 8989
    # for security reasons bind to localhost
    bindHost: localhost
  adminConnectors:
  - type: http
    port: 8990
    bindHost: localhost
```

I tried even copying the srtmprovider folder of my graphhopper (since I'm using the same .osm.pbf file to use map-matching library), but it made no difference.

The map matching is working, but the elevation data is never attached.

Could anyone help me please? I'd use the graphhopper library to obtain the elevation data, but the GPX files I've got have thousands of points, and I'd like to map-match them, in order to remove inconsistencies with the reality, since the GPX files aren't exact.

Thanks in advance!!!
