### ISSUE TITLE
Additional CH config leads to error

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#178]
When I using the following config:

```
graphhopper:
  datareader.file: ""
  graph.location: graph-cache

  graph.flag_encoders: car|turn_costs=true

  profiles:
    - name: car
      vehicle: car
      weighting: fastest
      turn_costs: true
    - name: car_no_tc
      vehicle: car
      weighting: fastest

  profiles_ch: []

  profiles_lm:
    - profile: car
    - profile: car_no_tc
      preparation_profile: car

  routing.ch.disabling_allowed: true
  routing.lm.disabling_allowed: true
  ...
```

then everything works. But as soon as I use `profiles_ch: [car_no_tc]` the error is thrown:

```
Cannot find LM preparation for the requested profile: 'car_no_tc'
You can try disabling LM using lm.disable=true available LM profiles: [car, small_truck, truck, scooter] -
for url http://localhost:8989/match?vehicle=car
```

Using `profile=car_no_tc` or `profile=car` in the URL does not help. Also strange: when I use `profile=car` the error message is still:

> Cannot find LM preparation for the requested profile: 'car_no_tc'
